name: Metrics
on:
  schedule: [{cron: "0 0 * * 0"}] # Every week
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: "header, languages"
          plugin_languages: yes
